# Generated by Django 2.1.2 on 2019-01-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auto_generated',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
