# Generated by Django 2.1.2 on 2019-01-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190126_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='anonymous_user',
        ),
    ]
