# Generated by Django 2.1.2 on 2019-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_anonymous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
