# Generated by Django 2.1.2 on 2019-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='anonymous_user',
            field=models.IntegerField(default=0),
        ),
    ]
