# Generated by Django 2.1.7 on 2019-03-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190304_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_value',
            new_name='address',
        ),
    ]
