# Generated by Django 2.1.7 on 2019-03-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '__first__'),
        ('accounts', '0009_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cart.ShippingDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_saved_details',
            field=models.BooleanField(default=False),
        ),
    ]
