# Generated by Django 2.1.7 on 2019-03-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190305_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shipping_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.ShippingDetails'),
        ),
    ]
