# Generated by Django 2.1.7 on 2019-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '__first__'),
        ('accounts', '0015_auto_20190305_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_details',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_details',
            field=models.ManyToManyField(blank=True, to='cart.ShippingDetails'),
        ),
    ]
