# Generated by Django 2.1.7 on 2019-03-05 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190305_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_details',
        ),
    ]
