# Generated by Django 2.1.2 on 2019-03-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_shipping_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_details',
        ),
    ]
