# Generated by Django 2.1.2 on 2019-03-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_userprofile_use_saved_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_saved_details',
            field=models.BooleanField(default=False),
        ),
    ]
