# Generated by Django 2.1.2 on 2019-03-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_details_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
